---
name: "build container images"

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Set environment
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo "NAME=" >> $GITHUB_ENV
          echo "VERSION=${BRANCH//master/latest}" >> $GITHUB_ENV
          # Support for git tags
          if [ ${GITHUB_REF} != ${TAG} ]; then
            echo "VERSION=${TAG}" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./pod
          file: ./pod/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/pod:${{ env.VERSION }}